<%@ page contentType="text/html;charset=UTF-8" language="java" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>登录 - 票映汇衣橱</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css"></head><body>
<aside class="sidebar"><div class="sidebar-logo">票映汇<span>网上衣橱</span></div><ul class="sidebar-nav"><li><a href="${pageContext.request.contextPath}/clothes"><span class="icon">🏠</span>首页</a></li><li><a href="${pageContext.request.contextPath}/login.jsp"><span class="icon">🔑</span>登录</a></li><li><a href="${pageContext.request.contextPath}/register.jsp"><span class="icon">📝</span>注册</a></li></ul></aside>
<div class="main-wrap"><div class="content"><div class="form-card"><h2>用户登录</h2><c:if test="${not empty msg}"><div class="alert alert-error">${msg}</div></c:if><c:if test="${param.reg=='ok'}"><div class="alert alert-success">注册成功，请登录</div></c:if>
<div class="tabs"><button class="tab-btn active" onclick="switchTab('user')">👤 用户登录</button><button class="tab-btn" onclick="switchTab('phone')">📱 手机登录</button><button class="tab-btn" onclick="switchTab('admin')" id="adminTabBtn" style="color:#8B6914">⚙️ 管理员登录</button></div>
<form id="userForm" action="${pageContext.request.contextPath}/LoginServlet" method="post"><input type="hidden" name="loginType" value="username"><div class="form-group"><label>用户名</label><input type="text" name="username" required></div><div class="form-group"><label>密码</label><input type="password" name="password" required></div><button type="submit" class="btn btn-primary btn-block">登 录</button></form>
<form id="phoneForm" action="${pageContext.request.contextPath}/LoginServlet" method="post" style="display:none"><input type="hidden" name="loginType" value="phone"><div class="form-group"><label>手机号</label><input type="text" name="phone" required></div><div class="form-group"><label>密码</label><input type="password" name="password" required></div><button type="submit" class="btn btn-primary btn-block">登 录</button></form>
<form id="adminForm" action="${pageContext.request.contextPath}/LoginServlet" method="post" style="display:none"><input type="hidden" name="loginType" value="admin"><div style="background:#faf7f0;padding:16px;border-radius:10px;margin-bottom:16px;border-left:4px solid #8B6914"><p style="font-size:13px;color:#5c4a3a;margin:0">🔐 管理员登录入口<br><span style="font-size:11px;color:#8a7e72">请使用管理员账号登录后台管理系统</span></p></div><div class="form-group"><label>管理员账号</label><input type="text" name="username" required placeholder="输入管理员用户名"></div><div class="form-group"><label>管理员密码</label><input type="password" name="password" required placeholder="输入管理员密码"></div><button type="submit" class="btn btn-primary btn-block" style="background:#3e2e18;border-color:#3e2e18">进入后台</button></form>
<div class="form-footer">还没有账号？<a href="${pageContext.request.contextPath}/register.jsp">立即注册</a></div></div></div></div>
<script>function switchTab(t){document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));if(t==='admin'){document.getElementById('adminTabBtn').classList.add('active')}else{document.querySelectorAll('.tab-btn')[t==='user'?0:1].classList.add('active')}document.getElementById('userForm').style.display=t==='user'?'block':'none';document.getElementById('phoneForm').style.display=t==='phone'?'block':'none';document.getElementById('adminForm').style.display=t==='admin'?'block':'none';}</script></body></html>