<%@ page contentType="text/html;charset=UTF-8" language="java" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>登录 - 微订宝衣橱</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css"></head><body>
<header class="topbar"><div class="logo"><a href="${pageContext.request.contextPath}/clothes" style="color:#d45d3e">微订宝衣橱</a></div><ul class="nav-link"><li><a href="${pageContext.request.contextPath}/clothes">首页</a></li><li><a href="${pageContext.request.contextPath}/login.jsp">登录</a></li><li><a href="${pageContext.request.contextPath}/register.jsp">注册</a></li></ul></header>
<div class="form-card"><h2>登录</h2><c:if test="${not empty msg}"><div class="alert alert-error">${msg}</div></c:if><c:if test="${param.reg=='ok'}"><div class="alert alert-success">注册成功</div></c:if>
<div class="tab-switch"><button class="active" onclick="switchTab('user')">👤 用户</button><button onclick="switchTab('phone')">📱 手机</button><button onclick="switchTab('admin')" id="adminBtn" style="font-weight:700;color:#d45d3e">⚙️ 管理</button></div>
<form id="userForm" action="${pageContext.request.contextPath}/LoginServlet" method="post"><input type="hidden" name="loginType" value="username"><div class="form-group"><label>用户名</label><input type="text" name="username" required></div><div class="form-group"><label>密码</label><input type="password" name="password" required></div><button type="submit" class="btn btn-primary btn-block">登 录</button></form>
<form id="phoneForm" action="${pageContext.request.contextPath}/LoginServlet" method="post" style="display:none"><input type="hidden" name="loginType" value="phone"><div class="form-group"><label>手机号</label><input type="text" name="phone" required></div><div class="form-group"><label>密码</label><input type="password" name="password" required></div><button type="submit" class="btn btn-primary btn-block">登 录</button></form>
<form id="adminForm" action="${pageContext.request.contextPath}/LoginServlet" method="post" style="display:none"><input type="hidden" name="loginType" value="username"><div style="text-align:center;margin-bottom:18px"><span style="font-size:40px">🔐</span><p style="font-size:14px;color:#4a3228;font-weight:600;margin-top:8px">管理员登录</p><p style="font-size:11px;color:#a08070">请使用管理员账号登录后台</p></div><div class="form-group"><label>管理员账号</label><input type="text" name="username" required placeholder="管理员用户名"></div><div class="form-group"><label>管理员密码</label><input type="password" name="password" required placeholder="管理员密码"></div><button type="submit" class="btn btn-primary btn-block">进入后台</button></form>
<div class="form-footer"><a href="${pageContext.request.contextPath}/register.jsp">还没有账号？立即注册</a></div></div>
<script>function switchTab(t){document.querySelectorAll('.tab-switch button').forEach(b=>b.classList.remove('active'));if(t==='admin'){document.getElementById('adminBtn').classList.add('active')}else{document.querySelectorAll('.tab-switch button')[t==='user'?0:1].classList.add('active')}document.getElementById('userForm').style.display=t==='user'||t==='admin'?'block':'none';document.getElementById('phoneForm').style.display=t==='phone'?'block':'none';document.getElementById('adminForm').style.display=t==='admin'?'block':'none';}</script></body></html>