<%@ page contentType="text/html;charset=UTF-8" language="java" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>登录 - 智安行衣橱</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css"></head><body>
<nav class="nav-bar"><div class="logo"><a href="${pageContext.request.contextPath}/clothes" style="color:#1a2d35">智安行衣橱</a></div><ul class="nav-links"><li><a href="${pageContext.request.contextPath}/clothes">首页</a></li><li><a href="${pageContext.request.contextPath}/login.jsp">登录</a></li><li><a href="${pageContext.request.contextPath}/register.jsp">注册</a></li></ul></nav>
<div class="form-center"><h2>登录</h2><c:if test="${not empty msg}"><div class="alert alert-error">${msg}</div></c:if><c:if test="${param.reg=='ok'}"><div class="alert alert-success">注册成功，请登录</div></c:if>
<div class="tab-bar"><button class="tab-btn active" onclick="switchTab('user')">👤 用户</button><button class="tab-btn" onclick="switchTab('phone')">📱 手机</button><button class="tab-btn" onclick="switchTab('admin')" id="adminTab" style="border:2px solid #4a6d7c">⚙️ 管理员</button></div>
<form id="userForm" action="${pageContext.request.contextPath}/LoginServlet" method="post"><input type="hidden" name="loginType" value="username"><div class="form-group"><label>用户名</label><input type="text" name="username" required></div><div class="form-group"><label>密码</label><input type="password" name="password" required></div><button type="submit" class="btn btn-primary btn-block">登 录</button></form>
<form id="phoneForm" action="${pageContext.request.contextPath}/LoginServlet" method="post" style="display:none"><input type="hidden" name="loginType" value="phone"><div class="form-group"><label>手机号</label><input type="text" name="phone" required></div><div class="form-group"><label>密码</label><input type="password" name="password" required></div><button type="submit" class="btn btn-primary btn-block">登 录</button></form>
<form id="adminForm" action="${pageContext.request.contextPath}/LoginServlet" method="post" style="display:none"><input type="hidden" name="loginType" value="username"><div style="background:linear-gradient(135deg,#1a2d35,#243b44);color:#fff;padding:18px;border-radius:12px;margin-bottom:20px;text-align:center"><p style="font-size:14px;margin:0;font-weight:600">🔐 后台管理登录</p><p style="font-size:11px;opacity:.7;margin-top:4px">仅限管理员账号访问</p></div><div class="form-group"><label>管理员账号</label><input type="text" name="username" required placeholder="输入管理员用户名"></div><div class="form-group"><label>管理员密码</label><input type="password" name="password" required placeholder="输入管理员密码"></div><button type="submit" class="btn btn-primary btn-block" style="background:#1a2d35">进入后台管理系统</button></form>
<div class="form-footer"><a href="${pageContext.request.contextPath}/register.jsp">还没有账号？立即注册</a></div></div>
<script>function switchTab(t){document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));if(t==='admin'){document.getElementById('adminTab').classList.add('active')}else{document.querySelectorAll('.tab-btn')[t==='user'?0:1].classList.add('active')}document.getElementById('userForm').style.display=t==='user'||t==='admin'?'block':'none';document.getElementById('phoneForm').style.display=t==='phone'?'block':'none';document.getElementById('adminForm').style.display=t==='admin'?'block':'none';}</script></body></html>